### ISSUE TITLE
Villagers sometimes disapper

### ISSUE THREAD

**Issue by Trard** [xGinko/VillagerOptimizer#8]
Villagers sometimes disappear, but i'm not sure that's your issue

Also I have this error in logs, probably related:

[11:45:39] [Region Scheduler Thread #3/ERROR]: [ca.spottedleaf.moonrise.common.util.TickThread] Thread Region Scheduler Thread #3 failed main thread check: Accessing poi chunk off-main
java.lang.Throwable: null
        at ca.spottedleaf.moonrise.common.util.TickThread.ensureTickThread(TickThread.java:51) ~[folia-1.21.jar:1.21-DEV-177c892]
        at net.minecraft.world.entity.ai.village.poi.PoiManager.getOrLoad(PoiManager.java:90) ~[folia-1.21.jar:1.21-DEV-177c892]
        at net.minecraft.world.entity.ai.village.poi.PoiManager.exists(PoiManager.java:350) ~[folia-1.21.jar:1.21-DEV-177c892]
        at net.minecraft.world.entity.ai.behavior.GoToPotentialJobSite.lambda$stop$2(GoToPotentialJobSite.java:52) ~[folia-1.21.jar:1.21-DEV-177c892]
        at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraft.world.entity.ai.behavior.GoToPotentialJobSite.stop(GoToPotentialJobSite.java:47) ~[folia-1.21.jar:1.21-DEV-177c892]
        at net.minecraft.world.entity.ai.behavior.GoToPotentialJobSite.stop(GoToPotentialJobSite.java:20) ~[folia-1.21.jar:1.21-DEV-177c892]
        at net.minecraft.world.entity.ai.behavior.Behavior.doStop(Behavior.java:91) ~[folia-1.21.jar:1.21-DEV-177c892]
        at net.minecraft.world.entity.ai.behavior.Behavior.tickOrStop(Behavior.java:80) ~[folia-1.21.jar:1.21-DEV-177c892]
        at net.minecraft.world.entity.ai.Brain.tickEachRunningBehavior(Brain.java:463) ~[folia-1.21.jar:1.21-DEV-177c892]
        at net.minecraft.world.entity.ai.Brain.tick(Brain.java:404) ~[folia-1.21.jar:1.21-DEV-177c892]
        at net.minecraft.world.entity.npc.Villager.customServerAiStep(Villager.java:258) ~[folia-1.21.jar:1.21-DEV-177c892]
        at net.minecraft.world.entity.npc.Villager.customServerAiStep(Villager.java:253) ~[folia-1.21.jar:1.21-DEV-177c892]
        at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:966) ~[folia-1.21.jar:1.21-DEV-177c892]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3489) ~[folia-1.21.jar:1.21-DEV-177c892]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:698) ~[folia-1.21.jar:1.21-DEV-177c892]
        at net.minecraft.world.entity.AgeableMob.aiStep(AgeableMob.java:155) ~[folia-1.21.jar:1.21-DEV-177c892]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3192) ~[folia-1.21.jar:1.21-DEV-177c892]
        at net.minecraft.world.entity.Mob.tick(Mob.java:465) ~[folia-1.21.jar:1.21-DEV-177c892]
        at net.minecraft.world.entity.npc.Villager.tick(Villager.java:300) ~[folia-1.21.jar:1.21-DEV-177c892]
        at net.minecraft.world.entity.Entity.rideTick(Entity.java:2985) ~[folia-1.21.jar:1.21-DEV-177c892]
        at net.minecraft.world.entity.LivingEntity.rideTick(LivingEntity.java:3745) ~[folia-1.21.jar:1.21-DEV-177c892]
        at net.minecraft.server.level.ServerLevel.tickPassenger(ServerLevel.java:1446) ~[folia-1.21.jar:1.21-DEV-177c892]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1411) ~[folia-1.21.jar:1.21-DEV-177c892]
        
Folia: 177c892
VillagerOptimizer: 1.6.1

**Comment by Trard** [comment]
I have a video, but nothing interesting there. Just a villager disappears right next to player (5 block radius)

**Comment by F3F5** [comment]
Folia 1.21 very very very beta.

**Comment by xGinko** [comment]
Hmm it would implicate that the plugin is calling getJobSite without scheduling it, I think I can fix it

**Comment by xGinko** [comment]
You wouldn't happen to use workstation optimization by any chance, would you?

**Comment by Trard** [comment]
> You wouldn't happen to use workstation optimization by any chance, would you?

I only use command optimization
